name: Push Docker Image to Azure and deploy to Azure

on:
  push:
    branches:
    - knex

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1.1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get vesion number
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
              export raw_version=$(az acr repository show-tags --name urkfarma --repository urk-farma --output tsv)
              export az_v_docker="${raw_version##*$'\n'}"
              arrIN=(${az_v_docker//./ })
              export az_v_docker="2.$((${arrIN[1]}+1))"
              echo "Pushing version ${az_v_docker}"
              echo "az_v_docker=${az_v_docker}" >> $GITHUB_ENV
      - name: Docker Login 
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.REGISTRY_URL }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker build and push
        run: |
          echo ${{ env.az_v_docker }}
          python3 createDockerfile.py ${{ secrets.SQL_server }} ${{ secrets.SQL_Password }} ${{ secrets.SQL_User }}
          docker build -t olliedev/urk-farma:${{ env.az_v_docker }} .
          docker tag olliedev/urk-farma:${{ env.az_v_docker }} urkfarma.azurecr.io/urk-farma:${{ env.az_v_docker }}
          docker push urkfarma.azurecr.io/urk-farma:${{ env.az_v_docker }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
            name: urkfarma
            resource-group: urk-frama
            dns-name-label: urk-farma
            ports: 443
            cpu: 1
            memory: 1.0
            image: urkfarma.azurecr.io/urk-frama:${{ env.az_v_docker }}
            registry-login-server: ${{ secrets.REGISTRY_URL }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            location: 'germanywestcentral'
